exports.version = '1.1.2'
exports.ids = [
    'New'
    'Open'
    'Save'
    'Save as'
    'Close'
    'Preferences'
    'Quit'
    'Undo'
    'Redo'
    'Cut'
    'Cut Special'
    'Copy'
    'Copy Special'
    'Paste'
    'Paste Special'
    'Duplicate'
    'Duplicate Special'
    'Group'
    'Ungroup'
    'Toggle Active'
    'Activate'
    'Deactivate'
    'Delete'
    'Delete Special'
    'Select All'
    'Unselect All'
    'Rename'
    'Click button'
    'Activate item'
    'Cancel Dialog'
    'Dialog: Yes'
    'Dialog: No'
    'Dialog: OK'
    'Delete character to left of cursor'
    'Delete character to right of cursor'
    'Insert new line'
    'Commit text'
    'Reload'
    'Previous history entry'
    'Next history entry'
    'Move cursor left'
    'Move cursor right'
    'Move cursor up'
    'Move cursor down'
    'Move cursor to start of document'
    'Move cursor to end of document'
    'Move cursor to start of line'
    'Move cursor to end of line'
    'Move cursor word left'
    'Move cursor word right'
    'Move cursor and extend selection left'
    'Move cursor and extend selection right'
    'Move cursor and extend selection up'
    'Move cursor and extend selection down'
    'Move cursor and extend selection to start of document'
    'Move cursor and extend selection to end of document'
    'Move cursor and extend selection to start of document'
    'Move cursor and extend selection to end of document'
    'Move cursor and extend selection word left'
    'Move cursor and extend selection word right'
    'Select first item'
    'Select last item'
    'move_selection_cursor_to_first_item'
    'move_selection_cursor_to_last_item'
    'move_selection_cursor_to_next_item'
    'move_selection_cursor_to_previous_item'
    'Extend selection range to first item'
    'Extend selection range to last item'
    'Extend selection to next item'
    'Extend selection range to previous item'
    'Extend selection to first item'
    'Extend selection to last item'
    'Select previous item'
    'Select next item'
    'Extend selection to next item'
    'Extend selection to previous item'
    'Toggle selection of item at cursor'
    'Select item in next lane'
    'Select item in previous lane'
    'Select item in first lane'
    'Select item in last lane'
    'Move cursor to next lane'
    'Move cursor to previous lane'
    'Move cursor to first lane'
    'Move cursor to last lane'
    'Extend selection to next lane'
    'Extend selection to previous lane'
    'Extend selection to first lane'
    'Extend selection to last lane'
    'Extend selection range to next lane'
    'Extend selection range to previous lane'
    'Extend selection range to first lane'
    'Extend selection range to last lane'
    'Select item to left'
    'Select item to right'
    'Select item above'
    'Select item below'
    'Move selection cursor left'
    'Move selection cursor right'
    'Move selection cursor up'
    'Move selection cursor down'
    'Extend selection range to item to left'
    'Extend selection range to item to right'
    'Extend selection range to item above'
    'Extend selection range to item below'
    'Extend selection to item to left'
    'Extend selection to item to right'
    'Extend selection to item above'
    'Extend selection to item below'
    'Focus panel to the left'
    'Focus panel to the right'
    'Focus panel above'
    'Focus panel below'
    'Focus next panel'
    'Focus previous panel'
    'Focus next field'
    'Focus previous field'
    'Focus widget to the left'
    'Focus widget to the right'
    'Focus widget above'
    'Focus widget below'
    'Toggle expanded state'
    'Zoom In'
    'Zoom Out'
    'Zoom to Fit'
    'Maximize window'
    'Minimize window'
    'Full screen'
    'Select Next Project'
    'Select Previous Project'
    'select_next_tab'
    'select_previous_tab'
    'Connect to Remote Project'
    'Show Controller Script Console'
    'help_user_guide'
    'help_user_guide_jp'
    'check_for_updates'
    'invoke_action'
    'Collect and Save'
    'Activate Engine For Project'
    'Create Instrument Track'
    'Create Audio Track'
    'Create Effect Track'
    'Create Scene'
    'Create Event'
    'Select previous track'
    'Select next track'
    'focus_track_header_area'
    'toggle_clip_launcher'
    'focus_or_toggle_clip_launcher'
    'Play Transport'
    'Continue Play Transport'
    'Play Transport From Start'
    'Stop Transport'
    'Play or Stop Transport'
    'Play or Pause Transport'
    'Continue Playback or Stop'
    'Play From Start or Stop Transport'
    'Toggle Record'
    'Tap Tempo'
    'Export Audio'
    'export_midi'
    'Select Pointer Tool'
    'select_time_selection_tool'
    'Select Pen Tool'
    'Select Eraser Tool'
    'Select Knife Tool'
    'toggle_browser_panel'
    'toggle_device_panel'
    'toggle_arranger'
    'toggle_detail_editor'
    'toggle_automation_editor'
    'toggle_mixer'
    'toggle_inspector'
    'toggle_studio_io'
    'toggle_song_panel'
    'focus_or_toggle_browser_panel'
    'focus_or_toggle_device_panel'
    'focus_or_toggle_arranger'
    'focus_or_toggle_detail_editor'
    'focus_or_toggle_automation_editor'
    'focus_or_toggle_mixer'
    'focus_or_toggle_inspector'
    'focus_or_toggle_studio_io'
    'focus_or_toggle_song_panel'
    'Switch to Mode 1'
    'Switch to Mode 2'
    'Switch to Mode 3'
    'Switch to Mode 4'
    'Select Next Mode'
    'Select Previous Mode'
    'Toggle maximized editing mode'
    'Select sub panel 1'
    'Select sub panel 2'
    'Select sub panel 3'
    'Select sub panel 4'
    'Select next sub panel'
    'Select previous sub panel'
    'Show Track Inputs and Outputs'
    'Show Sends'
    'Show Crossfades'
    'Show Effect Tracks'
    'Split'
    'Consolidate'
    'bounce_in_place'
    'bounce'
    'Transpose Semitone Down'
    'Transpose Semitone Up'
    'Transpose Octave Down'
    'Transpose Octave Up'
    'Quantize'
    'legato'
    'fixed_length'
    'Loop Selection'
    'Toggle Track Timeline vs. Clip Content Editing'
    'Toggle Arranger Cue Marker Visibility'
    'nudge_events_one_bar_earlier'
    'nudge_events_one_step_earlier'
    'nudge_events_one_bar_later'
    'nudge_events_one_step_later'
    'make_events_one_bar_shorter'
    'make_events_one_step_shorter'
    'make_events_one_bar_longer'
    'make_events_one_step_longer'
    'double_grid_size'
    'half_grid_size'
    'toggle_object_snapping'
    'toggle_absolute_grid_snapping'
    'toggle_relative_grid_snapping'
    'toggle_adaptive_grid'
    'prev_grid_subdivision'
    'next_grid_subdivision'
    'adjust_event_value_step_up'
    'adjust_event_value_step_down'
    'adjust_event_value_fine_step_up'
    'adjust_event_value_fine_step_down'
    'Create New Instrument'
    'Create New Audio Effect'
    'Create New Note Effect'
    'Create New Detector'
    'Nudge Left'
    'Nudge Right'
    'Nudge Up'
    'Nudge Down'
    'Nudge Left (coarse)'
    'Nudge Right (coarse)'
    'Nudge Up (coarse)'
    'Nudge Down (coarse)'
    'Increase Width'
    'Decrease Width'
    'Increase Height'
    'Decrease Height'
    'Bring To Front'
    'Send To Back'
    'focus_browser_search_field'
    'focus_file_overview'
    'focus_file_list'
    'toggle_preview_playback_of_selected_file'
    'open_containing_folder'
    'edit_file_meta_data'
    'Launch slot'
    'slice_to_drum_track'
    'slice_to_multi_sampler_track'
    'insert_silence'
    'cut_and_pull'
    'paste_and_push'
    'duplicate_and_push'
    'delete_and_pull'
    'toggle_folded_note_lanes'
    'toggle_double_or_single_row_track_height'
    'unlock_all_layers'
    'toggle_layer_lock'
    'toggle_layer_visibility'
]
